### ISSUE TITLE
Configuration block is not really scoped by engine

### ISSUE THREAD

**Issue by pinzonjulian** [amrani/rails_modular_monolith_demo#15]
Hi!

I was following your article on this topic and found out that when you run 
```ruby
ConnectBy.configure do |config|
  config.application_controller = "ApplicationController"
end
```

the object you `yield` is actually a subclass of `Rails::Engine`, not an instance of it. This means that if you have multiple initializers that configure multiple engines they're all going to overwrite whatever the previous initializer configured.

You can give it a try by adding another engine (let's say... `ChatBy`) and trying to setup a different `application_controller` for it. You'll find that now `ConnectBy` will have the `application_controller` you set for `ChatBy`.

**Comment by amrani** [comment]
Hey @pinzonjulian yes, you are right. I'd like to get around to updating the article and fixing this. PR's are welcome!

I think the simplest change would be to use `mattr_accessor`'s detailed in the rails docs. I have moved away from rails engines in favor of packages and leveraging [Packwerk](https://github.com/Shopify/packwerk).

**Comment by amrani** [comment]
Thanks again @pinzonjulian for pointing this out. I just pushed a [commit](https://github.com/amrani/rails_modular_monolith_demo/commit/ad66b185628f2bc651ce4a3918f4124cd4b07c9f).

**Comment by pinzonjulian** [comment]
Sure thing!

May I ask, why have you moved from engines? I've read a ton about it and about packwerk but I haven't found enough information about the drawbacks of engines. I know from experience that packwerk is super lightweight, much more flexible and much easier to start with but the developer experience that an engine provides, the feeling of working in a small rails app (engine) with all of the conventions it brings still feels like a compelling argument to me.

If you want to answer but not in this issue, feel free to message me in Twitter. My handle is @pinzonjulian

**Comment by amrani** [comment]
To clarify, I moved away from using engines as my main tool for defining domains. Both help in achieving modularization. I often still use engines and make each a package.

The main advantage of packages is that it is like a dial. You can turn it up and down depending on your needs. Using an engine is more all or none. At some point, the costs of turning the dial all the way up will outweigh the benefits - at least momentarily. Let me give you a real-world example: It's the holidays and we maintain a marketplace application. There is an opportunity to release a feature that will drive sales just in time for a holiday surge. The time-sensitive solution we came up with will introduce a circular dependency. `bundler` won't build. However, with packages, it will only document the violation. 

I like that packages stay out of the way but do an excellent job at catching and displaying violations. It is up to the developer to put in place the appropriate policies. Purely informative. 

Gem dependencies and migrations benefit as well. Testing is another key difference. Although, I wouldn't say it is a clear advantage. 

My short answer is that I recommend packwerk and packages for all applications. Including ones split up in engines.

**Comment by amrani** [comment]
And a lot less code. Here is a commit from moving an existing engine to a non-engine package
![Screen Shot 2021-12-27 at 10 44 58 AM](https://user-images.githubusercontent.com/5949323/147487102-4d701468-b04c-4b7c-a402-444c1990fd62.png)
